version: '3'
services:
  # db:
  #   image: postgres:11.5
  #   volumes:
  #     - ./server/postgres/data:/var/lib/postgresql/data:delegated
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - "5000:5432"
  db:
    image: mysql:8.0.21
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./server/mysql/data:/var/lib/mysql
      - ./mysql-confd:/etc/mysql/conf.d
  web:
    build:
      dockerfile: .docker/Dockerfile
      context: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./:/web
    ports:
      - "4000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
      DATABASE_USER: root
      DATABASE_PASSWORD: password
      DATABASE_PORT: 3306
      DATABASE_HOST: db